name = "Stheno"
uuid = "8188c328-b5d6-583d-959b-9690869a5511"
version = "0.6.7"

[deps]
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
ZygoteRules = "700de1a5-db45-46bc-99cf-38207098b444"

[compat]
BlockArrays = "0.12"
ChainRulesCore = "0.9"
Distances = "0.8, 0.9"
Distributions = "0.19, 0.20, 0.21, 0.22, 0.23"
FillArrays = "0.7, 0.8"
FiniteDifferences = "0.9"
Flux = "0.9, 0.10, 0.11"
MacroTools = "0.4, 0.5"
RecipesBase = "0.7, 0.8, 1"
Requires = "1"
Zygote = "0.5"
ZygoteRules = "0.2"
julia = "1.1.1"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[targets]
test = ["Documenter", "FiniteDifferences", "Test", "TimerOutputs", "Flux"]
